feat: Customize image screensavers
linuxdeepin/deepin-screensaver pull request #32
Opened 2022-09-22 09:23 UTC by obslee

Log: Customize image screensavers

2022-09-23 02:39 UTC, Clauszy requested changes

2022-09-23 02:39 UTC, Clauszy commented on src/com.deepin.CustomConfig.service
> +Name=com.deepin.CustomConfig
服务名不合规

2022-09-23 02:39 UTC, Clauszy commented on src/main.cpp
> +        isDialog = parser.isSet(optionConfig);
不匹配

2022-09-23 08:01 UTC, obslee commented on src/com.deepin.CustomConfig.service
> +Name=com.deepin.CustomConfig
ok

2022-09-23 08:02 UTC, obslee commented on src/main.cpp
> +        isDialog = parser.isSet(optionConfig);
done

2022-09-24 02:51 UTC, Clauszy requested changes

2022-09-24 02:51 UTC, Clauszy commented on src/com.deepin.CustomConfig.xml
> +<interface name='com.deepin.CustomConfig'>
文件名、服务名与代码中的不匹配

2022-09-24 02:51 UTC, Clauszy commented on src/dbuscustomconfig.h
> +    QWidget aaa;
代码规范

2022-09-24 02:51 UTC, Clauszy commented on src/main.cpp
> +        service = new DBusCustomConfig();
配置模式闲置后应自动退出

2022-09-24 02:51 UTC, Clauszy commented on src/dbuscustomconfig.cpp
> +
未对输入参数进行有效性校验

2022-09-24 02:51 UTC, Clauszy commented on src/main.cpp
> +        parser.addOption(optionConfig);
应该支持传参启动配置如：
deepin-screensaver --config name

2022-09-26 08:13 UTC, Johnson-zs requested changes

2022-09-26 08:13 UTC, Johnson-zs commented on src/com.deepin.screensaver.CustomConfig.service
> +Name=com.deepin.screensaver.CustomConfig
org.deepin

2022-09-27 01:55 UTC, Johnson-zs requested changes

2022-09-27 01:55 UTC, Johnson-zs commented on src/selectpathwidget.cpp
> +            // 如果配置的默认值是~，则恢复默认将触发该逻辑，此时纠正为homePath进行保存
~ 在DFileInfo应该是有处理的

2022-09-27 03:03 UTC, obslee commented on src/com.deepin.CustomConfig.xml
> +<interface name='com.deepin.CustomConfig'>
> 文件名、服务名与代码中的不匹配

done

2022-09-27 03:03 UTC, obslee commented on src/dbuscustomconfig.h
> +    QWidget aaa;
> 代码规范

done

2022-09-27 03:04 UTC, obslee commented on src/main.cpp
> +        service = new DBusCustomConfig();
> 配置模式闲置后应自动退出

在未存在配置界面的情况下，30s退出

2022-09-27 03:05 UTC, obslee commented on src/dbuscustomconfig.cpp
> +
> 未对输入参数进行有效性校验

done

2022-09-27 03:05 UTC, obslee commented on src/main.cpp
> +        parser.addOption(optionConfig);
> 应该支持传参启动配置如： deepin-screensaver --config name

done

2022-09-27 03:09 UTC, obslee commented on src/selectpathwidget.cpp
> +            // 如果配置的默认值是~，则恢复默认将触发该逻辑，此时纠正为homePath进行保存
DFileInfo是文管库的，屏保没有必要引入文管库

2022-09-27 05:14 UTC, obslee commented on src/com.deepin.screensaver.CustomConfig.service
> +Name=com.deepin.screensaver.CustomConfig
done

2022-09-29 03:01 UTC, closed without merging