fix: the issue of custom-screensaver screen display
linuxdeepin/deepin-screensaver pull request #35
Opened 2022-11-02 07:00 UTC by obslee

When there is no picture in custom-screensaver's Settings directory, the screensaver should display black

Log: fix the issue of custom-screensaver screen display
Bug: https://pms.uniontech.com/bug-view-167341.html

2022-11-04 08:41 UTC, Kakueeen commented on customscreensaver/deepin-custom-screensaver/deepin-custom-screensaver.pro
> +PKGCONFIG += x11 dtkwidget
新增了依赖，但是没有在control文件中添加依赖包

2022-11-04 08:51 UTC, Kakueeen commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
> +            index++;
该逻辑一直返回1

2022-11-04 09:04 UTC, obslee commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
> +            index++;
done

2022-11-07 01:24 UTC, Clauszy requested changes

2022-11-07 01:24 UTC, Clauszy commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
> +        auto indexPath = m_imagefiles.at(m_currentIndex);
检查越界？

2022-11-07 01:24 UTC, Clauszy commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
> +bool SlideshowScreenSaver::getCurrentImageIndex()
get接口应该返回的是index值。
接口名与实现不一致

2022-11-07 01:24 UTC, Clauszy commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
> +    if (fileInfo.isDir() && fileInfo.exists()) {
应该先判断是否存在

2022-11-07 10:21 UTC, lvwujun approved these changes

2022-11-08 03:38 UTC, misonlan approved these changes

2022-11-08 06:30 UTC, shzhuangpub approved these changes

2022-11-08 07:09 UTC, Clauszy approved these changes

2022-11-08 07:10 UTC, obslee commented
/merge

2022-11-08 07:10 UTC, merged