fix: In random mode, some images cannot be displayed for a long time
linuxdeepin/deepin-screensaver pull request #38
Opened 2022-11-11 10:26 UTC by obslee

1. Increase weight calculation
 2. Continuous same image processing

Log: fix In random mode, some images cannot be displayed for a long time
Bug: https://pms.uniontech.com/bug-view-168331.html

2022-11-15 02:22 UTC, Clauszy requested changes

2022-11-15 02:22 UTC, Clauszy commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.h
> +    bool m_HasAbnormal { false };
命名

2022-11-15 02:22 UTC, Clauszy commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.h
> +    QString lastImage;
命名

2022-11-15 02:22 UTC, Clauszy commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
> +            randomImageIndex();
递归风险。
少量图片（如只有两张）时有较高情况出现第一张一直是last

2022-11-15 02:22 UTC, Clauszy commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
> +                onUpdateImage();
递归风险。
当有大量文件都失效，堆栈会随着失效文件不断增加

2022-11-16 06:49 UTC, Clauszy approved these changes

2022-11-16 06:55 UTC, Kakueeen approved these changes

2022-11-16 06:55 UTC, obslee commented
/merge

2022-11-16 06:55 UTC, merged