fix: fix two bug of display
linuxdeepin/deepin-screensaver pull request #39
Opened 2022-11-16 07:48 UTC by obslee

1.Fixed the issue where playback would not loop when there were only two images
 2.Fixed the issue where uppercase suffixes were not supported

Log: fix bugs
Bug: https://pms.uniontech.com/bug-view-171197.html
     https://pms.uniontech.com/bug-view-172003.html

2022-11-17 06:38 UTC, Clauszy requested changes

2022-11-17 06:38 UTC, Clauszy commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
>              if (validSuffix.contains(info.suffix())) {
大小写不敏感即可

2022-11-17 06:46 UTC, obslee commented on customscreensaver/deepin-custom-screensaver/src/slideshowscreensaver.cpp
>              if (validSuffix.contains(info.suffix())) {
yeah!! done

2022-11-17 11:41 UTC, Clauszy approved these changes

2022-11-18 01:25 UTC, obslee commented
/merge

2022-11-18 01:25 UTC, merged